#!/bin/bash
#
# priority: 200
#
# Start local mail server.
#
# Mark Huang <mlhuang@cs.princeton.edu>
# Copyright (C) 2006 The Trustees of Princeton University
#

# Source function library and configuration
. /etc/plc.d/functions
. /etc/planetlab/plc_config

# Be verbose
set -x

case "$1" in
    start)
	if [ "$PLC_MAIL_ENABLED" != "1" ] ; then
	    exit 0
	fi

	MESSAGE=$"Starting mail server"
	dialog "$MESSAGE"

	# Add apache to list of users that can send mail as others
	# without a warning, so that the API can send out mail.
	count=$(grep ^apache /etc/mail/trusted-users|wc -l)
	if [ $count -eq 0 ] ; then
	        echo "apache" >>/etc/mail/trusted-users
	fi

	(exec 3>&- 4>&- ; service sendmail start)
	check

	result "$MESSAGE"
	;;

    stop)
	MESSAGE=$"Stopping mail server"
	dialog "$MESSAGE"

	service sendmail stop
	check

	result "$MESSAGE"
	;;
esac

exit $ERRORS
